"""Radar/rail geometry: parameters and the ideal straight-rail trajectory.

Coordinate convention matches torchbp's backprojection_polar_2d pixel formula
(x = r*sqrt(1-theta^2), y = r*theta, z = 0 ground plane; see
torchbp/csrc/cpu/backproj.cpp and imaging/README.md "PolarGrid-olion
rakenne"): z is up, the rail runs along the y axis, and ground-range targets
sit on the positive x axis.
"""

from dataclasses import dataclass

import torch

C0 = 299792458.0  # speed of light, m/s


@dataclass
class RadarParams:
    """FMCW radar and rail parameters, reference values from the Forsten
    scenario (docs/tehtavat/2026-07-11_vaihe0_imaging_runko.md)."""

    fc: float = 6.0e9       # carrier frequency, Hz
    bw: float = 300e6       # sweep bandwidth, Hz
    tsweep: float = 100e-6  # sweep duration, s
    fs: float = 10e6        # ADC sample rate, Hz
    oversample: float = 2.0  # range-compression FFT oversampling factor
    rail_length: float = 5.0  # nominal rail length, m
    altitude: float = 20.0    # radar height above the z=0 ground plane, m

    @property
    def wavelength(self) -> float:
        return C0 / self.fc

    @property
    def sample_spacing(self) -> float:
        """Along-rail spacing between sweeps, lambda/4."""
        return self.wavelength / 4

    @property
    def r_res(self) -> float:
        """Range-bin resolution of the range-compressed data, meters.

        For FMCW radar: c/(2*bw*oversample), matching the r_res argument
        expected by torchbp.ops.backprojection_polar_2d.
        """
        return C0 / (2 * self.bw * self.oversample)

    @property
    def nsamples(self) -> int:
        """Raw (pre-oversample) samples per sweep, as generated by
        torchbp.util.generate_fmcw_data."""
        return int(round(self.fs * self.tsweep))


def straight_rail_trajectory(params: RadarParams) -> torch.Tensor:
    """Ideal straight rail trajectory along the y axis at constant altitude.

    Sweeps are spaced by params.sample_spacing (lambda/4) and centered on
    y=0. Returns a [nsweeps, 3] float32 tensor (x=0, y=rail position,
    z=altitude).
    """
    n = int(round(params.rail_length / params.sample_spacing)) + 1
    y = params.sample_spacing * (torch.arange(n, dtype=torch.float32) - (n - 1) / 2)
    pos = torch.zeros((n, 3), dtype=torch.float32)
    pos[:, 1] = y
    pos[:, 2] = params.altitude
    return pos
